<?php

namespace Van\ResourceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlueprintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlueprintRepository extends EntityRepository
{
}
