<?php

namespace Van\ResourceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlueprintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlueprintRepository extends EntityRepository
{
    /**
     * get latest blueprints
     *
     * @param int $limit
     * @return array
     */
    public function getLatest($limit = 10)
    {
        $qb = $this->createQueryBuilder('bp')
        ->orderBy('bp.uploadedAt', 'DESC')
        ->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }
}
